<a href="https://colab.research.google.com/github/Isabela-Tellez/BootCampIA_Python/blob/main/Numpy/NumpySession%232.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importe Libreria NumPy
import numpy as np
np.__version__

'2.0.2'

ALGEBRA LINEAL NUMPY

In [3]:
#Creación primer Array
datos = np.array([10, 20, 30, 40])
datos

array([10, 20, 30, 40])

In [ ]:
#Valor:     10   20   30   40
#Posición:   0    1    2    3

In [4]:
#Muestreo de las 3 primera posiciones
datos[0:3]

array([10, 20, 30])

In [7]:
#Muestreo desde la primera posicion hasta la tercera
datos[1:4]


array([20, 30, 40])

MATRICES

In [5]:
matriz = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
matriz

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:

                          #Columna

#Valor:     10   20   30      0
#           40   50   60      1
#           70   80   90      2

#Fila:       0    1    2

In [6]:
#Extraer la primera fila
matriz[0]

array([10, 20, 30])

In [ ]:
#Antes de la coma(,) especifica la columna en este caso 2 y despues de la coma (,) indica la fila en este caso 1
matriz[0:3,1]

In [ ]:
#Extraer una columna
# : Muestra todos los elementos y el 1 indica cuál columna se quiere mostrar
matriz[:,1]

In [8]:
#Mostrar esta matriz
#   10, 20
#   40, 50
matriz[0:2, 0:2]

array([[10, 20],
       [40, 50]])

In [10]:
#Mostrar esta matriz
#   20, 30
#   50, 60
matriz[0:2, 1:3]

array([[20, 30],
       [50, 60]])

CREACIÓN DE CAFETERIA DIGITAL

In [12]:
#Creación de la matriz de la cafetería
#[cafés vendidos, croissants vendidos]
ventas = np.array([
    [10,5],#lunes
    [15,8],#martes
    [12,6],#miercoles
    [20,12],#jueves
    [25,15],#viernes
])
print("Nuestra tabla de ventas:")
print(ventas)

Nuestra tabla de ventas:
[[10  5]
 [15  8]
 [12  6]
 [20 12]
 [25 15]]


In [15]:
#Mostar la primera fila
ventas[0]

array([10,  5])

In [17]:
#Mostar la segunda columna
croissants_vendidos = ventas[:,1]
print(croissants_vendidos)

[ 5  8  6 12 15]


In [20]:
ventas_inicio_semana = ventas [0:2, :]
print("Solo Lunes y Martes")
print(ventas_inicio_semana)

Solo Lunes y Martes
[[10  5]
 [15  8]]


Array Broadcasting

In [22]:
a = np.array([1, 2, 3])
b = 2

#SUMA
#Suma a cada elemento del array 2
result = a + b
print(result)

[3 4 5]


In [23]:
#MATRIZ
#Le suma la dimension del arr a cada dimension de la matriz
arr = np.array([1, 2, 3])
matriz =np.array([
    [1, 2, 3],
    [4, 5, 6]])

result = arr + matriz
print(result)

[[2 4 6]
 [5 7 9]]


MEGAFONO MATEMÁTICO

In [24]:
#Creación de la matriz de la cafetería
#[cafés vendidos, croissants vendidos]
ventas = np.array([
    [10,5],#lunes
    [15,8],#martes
    [12,6],#miercoles
    [20,12],#jueves
    [25,15],#viernes
])
print("Nuestra tabla de ventas:")
print(ventas)

Nuestra tabla de ventas:
[[10  5]
 [15  8]
 [12  6]
 [20 12]
 [25 15]]


In [25]:
#Sumar .50 a cada precio
ventas_ajuste = ventas + 0.50
print("Precios ajustados por 0.50")
print(ventas_ajuste)

Precios ajustados por 0.50
[[10.5  5.5]
 [15.5  8.5]
 [12.5  6.5]
 [20.5 12.5]
 [25.5 15.5]]


Sistemas Lineales


In [34]:
#Código Sistemas Lineales

#A Array
A = np.array([
    [2,1],#lunes
    [1,1],#martes
])

#B De lo que se paga
B = np.array([5, 3])

result = np.linalg.solve(A, B)
print(f"Precio Café: {result[0]}")
print(f"Precio Croissant: {result[1]}")

Precio Café: 2.0
Precio Croissant: 1.0
