<a href="https://colab.research.google.com/github/Isabela-Tellez/BootCampIA_Python/blob/main/Numpy/NumpySession%231.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

VERIFICAR SI NUMPY ESTA INSTALADO


In [ ]:
#Verificación numpy instalado
!pip install numpy

#Importar libreria numpy como np
import numpy as np
print (f"Version de numpy: {np.__version__}")

Version de numpy: 2.0.2


METODOS LIBRERIA NUMPY

In [ ]:
list1 = [1, 2, 3, 4]
array = np.array([1, 2, 3, 4])

print("Tipo de objeto:", type(list1))
print("Tipo de objeto:", type(array))
print("Tipo de datos:", array.dtype)
print("Forma del array:", array.shape)
print("Numero total de elementos del array:", len(array))


Tipo de objeto: <class 'list'>
Tipo de objeto: <class 'numpy.ndarray'>
Tipo de datos: int64
Forma del array: (4,)
Numero total de elementos del array: 4


In [ ]:
#2D
ar2 = np.array([[1, 2, 3, 4], [4, 6, 7, 8]])
print(ar2)

[[1 2 3 4]
 [4 6 7 8]]


In [ ]:
# Con rangos (como range() de Python, pero devuelve un array)
#arrange
print (ar2)
np.arange(1,10,2) #Empieza en 1, tomando de dos en dos hasta 10

[[1 2 3 4]
 [4 6 7 8]]


array([1, 3, 5, 7, 9])

In [ ]:
#random
np.random.random((2,3)) #2filas, 3columnas Nums random 0-1

array([[0.43892097, 0.99977284, 0.26844765],
       [0.48176026, 0.30213984, 0.8326818 ]])

In [ ]:
#full
arfull = np.full (4, 10) #Se escribe 4 veces el segundo numero
print (arfull)

[10 10 10 10]


In [ ]:
#con valores equiespaciados
#linspace
arlin = np.linspace(0, 1, 5) #El 1er numero es el inicio, el 2do numero es el final, y el
                             #ultimo numero divide en este caso 5 veces equitativamente
print(arlin)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
#2D
ar2 = np.array([[1, 2, 3, 4], [4, 6, 7, 8]])
ar2


array([[1, 2, 3, 4],
       [4, 6, 7, 8]])

In [ ]:
print("shape:", ar2.shape) #Columnas y Filas
print("size", ar2.size) #Elementos del array
print("Dimensions:", ar2.ndim) #Dimension del array
print("Data Type:", array.dtype) #Tipo de dato del array

shape: (2, 4)
size 8
Dimensions: 2
Data Type: int64


OPERACIONES LIBRERIA NUMPY


In [ ]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a + 5 #Operaciones + - * /

array([ 6,  7,  8,  9, 10])

ACCEDER A ELEMENTOS (indexing)

In [ ]:
#acceder a los elementos (igual en las listas)
#Los indices empiezan en 0
a = np.array([1, 2, 3, 4, 5])
a

In [ ]:
print(a[0]) #Primera posicion

1


In [ ]:
print(a[4]) #Ultima posicion

print(a[-1]) #Otra manera de obtener Ultima posicion

5
5


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Elemento especifico de la fila1
print(a[0, 0])

1


In [ ]:
#Elemento especifico de la fila2
print(a[1, 1])

5


VECTORES


In [ ]:
#VECTORES
ventas = np.array([100, 200, 300])
costes = np.array([50, 80, 100])
ventas, costes

(array([100, 200, 300]), array([ 50,  80, 100]))

In [ ]:
beneficio = ventas - costes
beneficio

array([ 50, 120, 200])

MATRICES


In [ ]:
datos = np.array([
    [100, 50],
    [200, 80],
    [300, 100],
])
datos

array([[100,  50],
       [200,  80],
       [300, 100]])

In [ ]:
datos.shape #Filas y columnas de matriz

(3, 2)

In [ ]:
datos * 2 #Multiplica cada elemento de matriz * 2

array([[200, 100],
       [400, 160],
       [600, 200]])